<style>
    a:link,
    a:visited
    {
        color: white;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width: 100%;
        height: 100%;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
   
        height: 100%;


    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Mark's Homepage MADERFAKER!</span></h1>

    <h3>Click the link/Image below maderfaker</h3>

    <div id="more-information">
        <p> <?php echo " <a href='index/helloworld'> "; ?><img src="http://i.ytimg.com/vi/cOSkO10gjB4/hqdefault.jpg" /></a></p>
        <p>
         
            <?php echo " <a href='index/helloworld'> Click mo to go to Hell world!</a> "; ?></a>

        </p>
    </div>
</div>